docs: add issue, pull request template
aubergine-dance/courgette pull request #1
Opened 2024-11-11 17:22 UTC by chysis

2024-11-12 17:02 UTC, reddevilmidzy requested changes

2024-11-12 17:02 UTC, reddevilmidzy commented on .github/ISSUE_TEMPLATE/default.md
> +labels: ''
작은 따옴표로 하면 이런 에러가 발생하더라구요 😢 

![image](https://github.com/user-attachments/assets/c3041878-e66d-4327-86ef-43a7748bbd7f)


[참고](https://github.com/aubergine-dance/dance/blob/75dfd351d793c9111fb40acee495d8e6fb55eba7/.github/ISSUE_TEMPLATE/issue.md)

2024-11-13 08:10 UTC, chysis commented on .github/ISSUE_TEMPLATE/default.md
> +labels: ''
이런 에러가... 고맙습니다

2024-11-13 09:53 UTC, donghoony commented
잠시 머지 보류해주세요! [이런 기능](https://docs.github.com/ko/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)이 있어서 확인 중입니다 👍🏻

2024-11-13 09:57 UTC, donghoony commented
Organization의 중앙 repository인 [.github](https://github.com/aubergine-dance/.github)에 이슈 템플릿과 PR 템플릿을 추가했습니다.

2024-11-13 17:39 UTC, chysis commented
모두 정상 작동됩니다! 
백엔드 템플릿을 참고하면서 공통으로 만들어도 좋겠다 싶었는데, 방법이 있었군요🍆

2024-11-13 17:39 UTC, closed without merging